### ISSUE TITLE
IPv6 comaptibility

### ISSUE THREAD

**Issue by matzex** [clintjedwards/dht22_exporter#8]
Hi,
thank you very much for this exporter!
It works fine for me on my local network, but I would like to make the metrics available for a remote prometheus host and therefore my raspberry pi is using a IPv6 address. I tried to use the -a argument with an IPv6 address, but always get the following error:

> root@rpi3-pihole:/usr/local/bin# python3 /usr/local/bin/dht22_exporter.py -g 4 -i 2 -a [2001:470:...] -p 9618
Traceback (most recent call last):
  File "/usr/local/bin/dht22_exporter.py", line 64, in <module>
    main()
  File "/usr/local/bin/dht22_exporter.py", line 55, in main
    start_http_server(args.port, args.addr)
  File "/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py", line 148, in start_wsgi_server
    httpd = make_server(addr, port, app, ThreadingWSGIServer, handler_class=_SilentHandler)
  File "/usr/lib/python3.7/wsgiref/simple_server.py", line 153, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.7/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
socket.gaierror: [Errno -2] Name or service not known

Do you know if this project is already compatibel with IPv6. I think you are using the prometheus library and can't handle so much details of the network stack on yourself, but maybe you are having an idea how to fix this.
I am using Python 3.7.3.

Thank you very much
Matthias

**Comment by clintjedwards** [comment]
Hey! Unfortunately it is not tested with IPv6, there are no plans to add IPv6 support, and I'm pretty sure it blows up(as you've seen already if you try to use an IPV6 address). 

I assume the easiest solution would be if [this ticket](https://github.com/prometheus/client_python/issues/567) was fixed, then you could simply update the version and it would work. But the author of the package doesn't seem to like the available solutions and I wouldn't hold your breath for a fix. 

The alternative is implementing a custom webserver for those who want to use IPv6 and then duplicating the functionality of the default IPv4 webserver. I think(but am not sure) that Python already supports this so honestly it shouldn't all that bad. Essentially you'll just have to parse the address field for IPv6 formatted string and then write the http.server in the same exact way as the Prometheus library is written except for the fact that it supports IPv6. If things go really well you might even be able to convince the owner to create a separate function call for ipv6(something like `start_http_server_ipv6`).

I'm gonna close this for now since there is nothing further to do here, but if you have more questions feel free to reopen and/or ask them.
